# Generated by Django 5.0 on 2024-06-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytoManyExample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customers',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='manytoManyExample.customer')),
                ('product', models.ManyToManyField(related_name='product', to='manytoManyExample.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerProduct',
        ),
    ]
