# Generated by Django 5.0 on 2024-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytoManyExample', '0002_remove_product_customers_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('gr', 'Gram'), ('adet', 'Adet')], max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
