# Generated by Django 5.0 on 2024-06-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoOneExample', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='Profile',
        ),
    ]
