# Generated by Django 5.0 on 2024-06-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetoOneExample', '0002_rename_profil_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telefon_numarasi',
            new_name='telephone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='kullanici_adi',
            new_name='user_name',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='onetoOneExample.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Kullanici',
        ),
    ]
